name: Telegram Scraper Bot

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # آخرین نسخه پایدار

      - name: Set up Python
        uses: actions/setup-python@v5 # آپدیت شده از v4 به v5
        with:
          python-version: '3.11' # استفاده از نسخه جدیدتر پایتون

      - name: Set Node.js Env
        # این خط برای رفع هشداری که در عکس فرستادی اضافه شد
        run: echo "FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update proxies and v2ray configs: $(date)" || exit 0
          git push
